# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  host:  ec2-54-163-230-90.compute-1.amazonaws.com
  username: ncuzekbdjhhnqc
  password: h6kMifQhkAtiHCF87ZG93UQ4ib
  port: 5432
  database: d4kcjr5q7p0ui7

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username:
  password:

production:
    adapter: postgresql
    host:  ec2-54-163-230-90.compute-1.amazonaws.com
    username: ncuzekbdjhhnqc
    password: h6kMifQhkAtiHCF87ZG93UQ4ib
    port: 5432
    database: d4kcjr5q7p0ui7

cucumber:
  <<: *TEST
